### PR TITLE
Add Dark Theme Toggle Button

### PR DESCRIPTION
**Pull request by Amaanx6**
This pull request implements a dark theme toggle button in the header of the website. The button has been styled to display a moon emoji 🌙 when in light mode and a sun emoji ☀️ when in dark mode.
### Changes Made:

- Added a button to toggle between light and dark themes.

- Updated the HTML to include the emoji for the toggle button.
- Styled the button for improved aesthetics and hover effects.

- Implemented JavaScript functionality to switch themes and change the emoji accordingly.

- The dark theme can be further customized by adjusting the CSS styles.

### Screenshots : 
Screenshot 2024-10-18 002911

### CODE REVIEW

**Comment by Mohfazam** [comment]
The main title text isn't visible when toggled in dark mode.

**Comment by Mohfazam** [comment]
Screenshot 2024-10-18 005536
Screenshot 2024-10-18 005524
Screenshot 2024-10-18 005509
Screenshot 2024-10-18 005458

**Comment by Amaanx6** [comment]
> The main title text isn't visible when toggled in dark mode.

Thank you for pointing that out! I've updated the dark mode styles to ensure the main title text is now visible. The issue should be resolved with the new styling. Let me know if it looks good on your end!"
Screenshot 2024-10-18 010059

**Comment by Mohfazam** [comment]
Appreciate your efforts and dedication. but the approach of changing the colors manually will clutter the codebase. 
The better approach will be to store the color codes in variables and toggling them using JavaScript.
But targeting the exact elements and toggling their colors are crucial, Your most recent changes toggles the body background but they are not in sync with other elements. 

Screenshot 2024-10-18 010042
Screenshot 2024-10-18 010028
Screenshot 2024-10-18 010019
Screenshot 2024-10-18 010003

**Comment by Amaanx6** [comment]
> Appreciate your efforts and dedication. but the approach of changing the colors manually will clutter the codebase. The better approach will be to store the color codes in variables and toggling them using JavaScript.

Thank you for the suggestion! I agree that using variables would indeed keep the code cleaner and more maintainable. I'll go ahead and refactor the color definitions into CSS variables and update the JavaScript to toggle them dynamically. This will help avoid hardcoding colors and make the theme switching more scalable in the future. Appreciate your feedback!

**Pull request closed without merging**
